name: "Saint Andiol Musique SAM"
description: "Description courte de ton association"
url: "https://saintandiolmusique.github.io/SAM/"  # À remplacer par ton URL GitHub Pages
title: "Saint Andiol Musique SAM"
email: "standiolmusique@gmail.com"
author: "SAM"

# Paramètres pour Jekyll
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Menu de navigation
header_pages:
  - index.md
  - about.md
  - news.md
  - contact.md

# Réseaux sociaux (optionnel)
social:
  facebook: "https://facebook.com/ton-association"
  twitter: "https://twitter.com/ton-association"
  instagram: "https://instagram.com/ton-association"
